LIST_TEXTS = [
    "The time is never right.<br>Make it right.",
    "Just get it<br>DONE",
	"Learn something today.",
    "Each challenge<br>makes you smarter.",
    "Pareto.",
    "Focuse on one thing.<br>Do it right.",
    "Be productiv,<br>not busy.",
    "Be efficient.",
    "Don't do more,<br>focus on less.",
    "Don't spend time,<br>use it.",
    "Your attention<br>is VALUABLE.",
    "You don't fail<br>if you don't try.",
    "Great acts<br>are made up of<br>small deeds.",
    "Small steps<br>matter.",
    "Effective performance is preceded<br>by painstaking preparation",
    "What we fear doing most<br>is usually what we most need to do.",
    "The best way out<br>is always through.",
    "Identify the essential.<br>Eliminate the rest.",
    "Do what’s necessary.<br>Then do what’s possible.<br>Suddenly you're doing the impossible.",
    "Just make the first smallest step.<br>Action causes motivation.",
    "Objects in motion<br>tend to stay in motion.",
    "Find a way to get started<br>in less than two minutes.",
    "It's survival of the fittest,<br>not the strongest.",
	"Do the hard job first.",
    "Make each day your masterpiece.",
    "Start tomorrow today.",
    "Break it into smaller pieces.",
    "If it takes less then 2 min<br>do it right now.",
    "Focus on what you control.<br>Everything else is not worth your time.",
    "Strict with yourself,<br>tolerant with others.",
    "Be comfortable<br>being uncomfortable.",
    "Eat that frog.",
    "80/20",
    "Do it what if you say it.<br>Only say what you are willing to do.",
    "Don't complain.<br>Create solutions.",
    "You can't control everythin.<br>But you can control how you react."
]